table CostCenter_Dim2
	lineageTag: 42a522b6-50f9-4f1d-bbc1-15279121e7e7

	column 'Código de centro de coste'
		dataType: string
		lineageTag: 190340f6-013a-4f97-aff0-8285592c3573
		summarizeBy: none
		sourceColumn: Código de centro de coste

		annotation SummarizationSetBy = Automatic

	column 'Código de dimensión del centro de costes'
		dataType: int64
		formatString: 0
		lineageTag: 7e4d49cc-d884-48e4-b759-5737eaf0a26a
		summarizeBy: sum
		sourceColumn: Código de dimensión del centro de costes

		annotation SummarizationSetBy = Automatic

	column 'Nombre de centro de coste'
		dataType: string
		lineageTag: b76b6bf2-597d-4f90-947c-940205ef4a41
		summarizeBy: none
		sourceColumn: Nombre de centro de coste

		annotation SummarizationSetBy = Automatic

	partition CostCenter_Dim2 = m
		mode: import
		source =
				let
				    Origen = SapHana.Database("192.168.0.231:30015", [Implementation="2.0"]),
				    Contents = Origen{[Name="Contents"]}[Data],
				    sap.sbololasucursal.adm = Contents{[Name="sap.sbololasucursal.adm"]}[Data],
				    CostCenter1 = sap.sbololasucursal.adm{[Name="CostCenter"]}[Data],
				    #"Elementos agregados" = Cube.Transform(CostCenter1,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[CostCenter]", {"[CostCenter].[CostCenterCode]", "[CostCenter].[CostCenterDimensionCode]", "[CostCenter].[CostCenterName]"}, {"Código de centro de coste", "Código de dimensión del centro de costes", "Nombre de centro de coste"}}
				        }),
				    #"Filas filtradas" = Table.SelectRows(#"Elementos agregados", each ([Código de dimensión del centro de costes] = 2))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

