table MedidasRetail
	lineageTag: 7d3be7f7-79d1-498c-bd82-0b3cb9d5d001

	measure Ventas = SUM(LOL_PBISGIRETAIL[LineTotal])
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 5a40a7f9-5cd4-4cef-acd7-1b88cd2a30d4

	measure Ventas_YTD = [Ventas]
		formatString: "€"\ #,0.0;-"€"\ #,0.0;"€"\ #,0.0
		lineageTag: 4c3f3215-d6c8-47d9-833c-d2c6e94da448

	measure Ventas_YTD_LY =
			VAR FechasLY =
				SELECTCOLUMNS(
					VALUES(Calendario[Date]),
					"Date", Calendario[Date] - 364
				)
			RETURN
				CALCULATE(
					[Ventas],
					REMOVEFILTERS(Calendario[Date]),
					TREATAS(FechasLY, Calendario[Date])
				)
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: d40df2eb-853f-45d8-aa6b-f8481968cb29

	measure Ventas_YTD_Var = [Ventas_YTD] - [Ventas_YTD_LY]
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 166845a7-8ea8-4c2b-b3a0-dfa9506672bb

	measure Ventas_YTD_Var_% =
			DIVIDE(
				[Ventas_YTD] - [Ventas_YTD_LY],
				[Ventas_YTD_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7faa5831-ab3b-4cb0-8546-6dab58452a7a

	measure Ventas_SinIVA = SUM(LOL_PBISGIRETAIL[LineTotalWithoutTax])
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: adb82b7b-e87f-41bc-b18b-55ab50f401f8

	measure Ventas_SinIVA_YTD = [Ventas_SinIVA]
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 6d93d40d-bab1-4ce6-90a8-1a4091376f35

	measure Ventas_SinIVA_YTD_LY =
			VAR FechasLY =
				SELECTCOLUMNS(
					VALUES(Calendario[Date]),
					"Date", Calendario[Date] - 364
				)
			RETURN
				CALCULATE(
					[Ventas_SinIVA],
					REMOVEFILTERS(Calendario[Date]),
					TREATAS(FechasLY, Calendario[Date])
				)
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 165eea4f-5145-42c5-b1d2-c85f6ccee89a

	measure Ventas_SinIVA_YTD_Var = [Ventas_SinIVA_YTD] - [Ventas_SinIVA_YTD_LY]
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 05409390-8e48-4608-b2dc-36f01cf8799c

	measure Ventas_SinIVA_YTD_Var_% =
			DIVIDE(
				[Ventas_SinIVA_YTD] - [Ventas_SinIVA_YTD_LY],
				[Ventas_SinIVA_YTD_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: db74c990-bf50-4fe5-a35e-000671e01b79

	measure Cantidad = SUM(LOL_PBISGIRETAIL[Quantity])
		formatString: 0.00
		lineageTag: 0d9ef0ef-1a29-4c13-8f46-5f55e7a8a101

	measure Cantidad_YTD = [Cantidad]
		formatString: 0.00
		lineageTag: 0d9ef0ef-1a29-4c13-8f46-5f55e7a8a102

	measure Cantidad_YTD_LY =
			VAR FechasLY =
				SELECTCOLUMNS(
					VALUES(Calendario[Date]),
					"Date", Calendario[Date] - 364
				)
			RETURN
				CALCULATE(
					[Cantidad],
					REMOVEFILTERS(Calendario[Date]),
					TREATAS(FechasLY, Calendario[Date])
				)
		formatString: 0.00
		lineageTag: 0d9ef0ef-1a29-4c13-8f46-5f55e7a8a103

	measure Cantidad_YTD_Var = [Cantidad_YTD] - [Cantidad_YTD_LY]
		formatString: 0.00
		lineageTag: 0d9ef0ef-1a29-4c13-8f46-5f55e7a8a104

	measure Cantidad_YTD_Var_% =
			DIVIDE(
				[Cantidad_YTD] - [Cantidad_YTD_LY],
				[Cantidad_YTD_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0d9ef0ef-1a29-4c13-8f46-5f55e7a8a105

	measure NumeroTransacciones =
			CALCULATE(
				DISTINCTCOUNT(LOL_PBISGIRETAIL[Ticket]),
				NOT LOL_PBISGIRETAIL[TipoDocumento] IN {"VTD", "VRMA"}
			)
		formatString: 0
		lineageTag: 12345678-1234-1234-1234-123456789abc

	measure NumeroTransacciones_YTD = [NumeroTransacciones]
		formatString: 0
		lineageTag: 60e5bd21-b9ce-46d8-9650-b9a903e116f0

	measure NumeroTransacciones_LY =
			VAR FechasLY =
				SELECTCOLUMNS(
					VALUES(Calendario[Date]),
					"Date", Calendario[Date] - 364
				)
			RETURN
				CALCULATE(
					[NumeroTransacciones],
					REMOVEFILTERS(Calendario[Date]),
					TREATAS(FechasLY, Calendario[Date])
				)
		formatString: 0
		lineageTag: 12345678-1234-1234-1234-123456789abd

	measure NumeroTransacciones_Var = [NumeroTransacciones_YTD] - [NumeroTransacciones_LY]
		formatString: 0
		lineageTag: 9dbf914a-2daa-4020-bb37-cdb26ed7b810

	measure NumeroTransacciones_Var_% =
			DIVIDE(
				[NumeroTransacciones_YTD] - [NumeroTransacciones_LY],
				[NumeroTransacciones_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 12345678-1234-1234-1234-123456789abe

	measure PromedioVentaTransaccion = DIVIDE([Ventas], [NumeroTransacciones])
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 87654321-4321-4321-4321-fedcba987654

	measure PromedioVentaTransaccion_YTD = DIVIDE([Ventas_YTD], [NumeroTransacciones_YTD])
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: a3b9e760-d783-4e04-9ed9-e7223a97433b

	measure PromedioVentaTransaccion_LY = DIVIDE([Ventas_YTD_LY], [NumeroTransacciones_LY])
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: 87654321-4321-4321-4321-fedcba987655

	measure PromedioVentaTransaccion_Var = [PromedioVentaTransaccion_YTD] - [PromedioVentaTransaccion_LY]
		formatString: #,0.00;-#,0.00;#,0.00
		lineageTag: e85a0742-b4da-427e-a55f-32c41c02c6cd

	measure PromedioVentaTransaccion_Var_% =
			DIVIDE(
				[PromedioVentaTransaccion_YTD] - [PromedioVentaTransaccion_LY],
				[PromedioVentaTransaccion_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 87654321-4321-4321-4321-fedcba987656

	measure NumeroClientesUnicos = DISTINCTCOUNT(LOL_PBISGIRETAIL[Cliente])
		formatString: 0
		lineageTag: abcdef12-3456-7890-abcd-ef1234567890

	measure NumeroClientesUnicos_YTD = [NumeroClientesUnicos]
		formatString: 0
		lineageTag: a36c46db-510c-4f5b-a7f4-88f09af78434

	measure NumeroClientesUnicos_LY =
			VAR FechasLY =
				SELECTCOLUMNS(
					VALUES(Calendario[Date]),
					"Date", Calendario[Date] - 364
				)
			RETURN
				CALCULATE(
					[NumeroClientesUnicos],
					REMOVEFILTERS(Calendario[Date]),
					TREATAS(FechasLY, Calendario[Date])
				)
		formatString: 0
		lineageTag: 1093eec0-9198-4924-88ee-b04597d0f2ec

	measure NumeroClientesUnicos_Var = [NumeroClientesUnicos_YTD] - [NumeroClientesUnicos_LY]
		formatString: 0
		lineageTag: 75875d66-f1b4-4c03-b83a-80d8ee50adfc

	measure NumeroClientesUnicos_Var_% =
			DIVIDE(
				[NumeroClientesUnicos_YTD] - [NumeroClientesUnicos_LY],
				[NumeroClientesUnicos_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c1888c60-7424-46b1-b0a4-31df2c2f3c9b

	measure UPT = DIVIDE([Cantidad], [NumeroTransacciones])
		formatString: 0.0
		lineageTag: abcdef12-3456-7890-abcd-ef1234567891

	measure UPT_YTD = DIVIDE([Cantidad_YTD], [NumeroTransacciones_YTD])
		formatString: 0.0
		lineageTag: 79cd9e27-a5b1-4d64-8a20-5400a0c9d915

	measure UPT_LY = DIVIDE([Cantidad_YTD_LY], [NumeroTransacciones_LY])
		formatString: 0.0
		lineageTag: abcdef12-3456-7890-abcd-ef1234567892

	measure UPT_Var = [UPT_YTD] - [UPT_LY]
		formatString: 0.0
		lineageTag: ed612a78-a69e-4c35-9b33-cf65acef6828

	measure UPT_Var_% =
			DIVIDE(
				[UPT_YTD] - [UPT_LY],
				[UPT_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: abcdef12-3456-7890-abcd-ef1234567893

	column Column
		formatString: 0
		lineageTag: 13ad3775-564d-4a81-b8af-26617529fef9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition MedidasRetail = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 70e735ff6fb1447283f702adfe82c501

